### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by gorazdko** [BlockchainCommons/bc-lifehash-cli#1]
## Abstract

Build fails on MacOS

https://github.com/gorazdko/bc-lifehash-cli/runs/1906095231?check_suite_focus=true

To test please build in a clean environment without pre-installed libraries

**Comment by gorazdko** [comment]
ping @wolfmcnally

**Comment by wolfmcnally** [comment]
@gorazdko Unable to replicate. Please open another issue be more specific about the error you are receiving.

**Comment by wolfmcnally** [comment]
I see where you ran into the issue [here](https://github.com/gorazdko/bc-lifehash-cli/runs/1906095231?check_suite_focus=true#step:4:506). But it does work on my Mac, so unless you need specific further help I'll let you look more closely at the CI environment.

**Comment by gorazdko** [comment]
I am very specific.

Did you click the link and read the logs? https://github.com/gorazdko/bc-lifehash-cli/runs/1906095231?check_suite_focus=true

**Comment by gorazdko** [comment]
> But it does work on my Mac

Yes because you have preinstalled libraries.

**Comment by wolfmcnally** [comment]
I need you to be more specific here in the issue.

**Comment by ChristopherA** [comment]
I've run into this type of thing before — you often have libraries that you have `make install`ed before, or are in a path that isn't set up on other platforms. His problem is that something in your code is relying on that library to be already available, when it might not be.

**Comment by wolfmcnally** [comment]
OK, let me try to be very clear here.

![image](https://user-images.githubusercontent.com/676176/110047512-dd3b7500-7d02-11eb-895a-22ffd1f30740.png)

This is the error from the logs. It is not (apparently) erroring because of a missing library, but because it can't find a header for *this* library. This would, to me, indicate a misconfiguration of the build script. On my system this header, is *not* installed in my system paths, but *is* installed locally as part of the submodules that the build script installs. So based on this error message, I *DO NOT SEE* how this is at all related to other dependencies installed on my system, and I am asking you, @gorazdko , to make this clear to me, as you seem pretty clear about it. I am *not* able to replicate this issue.

So, please advise.

**Comment by gorazdko** [comment]
~You're right GH actions has problems executing zsh with macos instance and simply changing the evnironment to bash doesn't work either.~

Since zsh is not widely present on different platforms (Linux) I will not be supporting it.

**Comment by gorazdko** [comment]
Looks like the bug is on your side:

The correct shebang is `#!/bin/zsh` whereas you are using  `#!zsh`. Then it works.
